/* ---------------------------------------------------------------------------
 * AUTO-INGESTED FINDINGS  --  GENERATED by refresh_calendar.py. Do not hand-edit.
 *
 * Discovered via Wayback CDX, read via X's public syndication endpoint, fields
 * extracted from caption TEXT ONLY. Every entry carries provenance:"auto" and
 * is UNREVIEWED -- it is a separate layer so a bad extraction stays visible and
 * toggleable instead of blending into the curated layers.
 *
 * Append-only. Re-running never rewrites or renumbers an existing entry, so
 * user_overlay notes and hides (keyed to post_id) survive every refresh.
 * --------------------------------------------------------------------------- */

window.CALENDAR_ENTRIES = window.CALENDAR_ENTRIES || [];
window.CALENDAR_ENTRIES.push.apply(window.CALENDAR_ENTRIES, [
 {
  "date": "2026-08-20",
  "type": "auto_finding",
  "label": "Auto Finding",
  "category": "Auto Finding",
  "fields": {
   "post_id": "2090547154876301664",
   "ticker": "HIBL",
   "price": null,
   "action": null,
   "co_executed": null,
   "outfit": "HIBL because of this specific outfit",
   "ma_designation": null,
   "timeframe": null,
   "has_media": false,
   "provenance": "auto",
   "ingested": "2026-08-28",
   "note": "auto-ingested from text; UNREVIEWED"
  }
 },
 {
  "date": "2026-08-20",
  "type": "auto_finding",
  "label": "Auto Finding",
  "category": "Auto Finding",
  "fields": {
   "post_id": "2090582182117130610",
   "ticker": "HIBL",
   "price": "120.00",
   "action": null,
   "co_executed": null,
   "outfit": "21/42/83/116/332/664 / MA83",
   "ma_designation": "21/42/83/116/332/664 / MA83",
   "timeframe": null,
   "has_media": false,
   "provenance": "auto",
   "ingested": "2026-08-28",
   "note": "auto-ingested from text; UNREVIEWED"
  }
 },
 {
  "date": "2026-08-25",
  "type": "auto_finding",
  "label": "Auto Finding",
  "category": "Auto Finding",
  "fields": {
   "post_id": "2092328733315363215",
   "ticker": "IXIC",
   "price": "120.00",
   "action": null,
   "co_executed": "HIBL",
   "outfit": "20/100 / MA100 MA83",
   "ma_designation": "20/100 / MA100 MA83",
   "timeframe": "2h",
   "has_media": false,
   "provenance": "auto",
   "ingested": "2026-08-28",
   "note": "auto-ingested from text; UNREVIEWED"
  }
 }
]);
