/* ---------------------------------------------------------------------------
 * AUTO-INGESTED FINDINGS  --  GENERATED by refresh_calendar.py. Do not hand-edit.
 *
 * Empty until the first daily run finds a qualifying post. Present so index.html
 * can load it unconditionally. Uses push.apply, like the other layers -- a plain
 * push(array) would append the ARRAY as a single bogus entry.
 * --------------------------------------------------------------------------- */

window.CALENDAR_ENTRIES = window.CALENDAR_ENTRIES || [];
window.CALENDAR_ENTRIES.push.apply(window.CALENDAR_ENTRIES, []);
