r"""Bake SPX daily OHLC into prices.js for the calendar. Run again to refresh.

Reads credentials from C:\Users\ssagl\Documents\sma-alerts\.env via that folder's
ts_client. Nothing secret is written here -- prices.js is derived market data only.

Symbol is $SPX.X, the same symbol config.py already uses. Daily bars carry a
20:00/21:00 UTC timestamp (16:00 ET session close), so the UTC date IS the ET
session date; no timezone shifting is needed or wanted.

The current session is skipped while the market is still open -- a partial bar's
high/low is not the day's high/low, and showing it would be quietly wrong.
"""
import platform
platform._wmi = None          # wedged WMI provider on this PC; pandas blocks forever without it

import sys, os, json, datetime, zoneinfo

ENGINE = r"C:\Users\ssagl\Documents\sma-alerts"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prices.js")
SYMBOL = "$SPX.X"
FIRST = "2021-11-01"          # calendar's earliest entry is 2021-12; pull a little before

sys.path.insert(0, ENGINE)
from ts_client import TradeStationClient

ET = zoneinfo.ZoneInfo("America/New_York")
now_et = datetime.datetime.now(ET)
today_et = now_et.date()
market_open_now = (now_et.weekday() < 5 and
                   datetime.time(9, 30) <= now_et.time() < datetime.time(16, 0))

c = TradeStationClient()
df = c.get_bars(SYMBOL, 1, unit="Daily", firstdate=FIRST,
                lastdate=today_et.isoformat())
if not len(df):
    raise SystemExit("no bars returned -- aborting without touching prices.js")

rows, skipped = {}, None
for ts, r in df.iterrows():
    d = ts.date()                                   # UTC date == ET session date for daily bars
    if d == today_et and market_open_now:
        skipped = d
        continue
    rows[d.isoformat()] = {"o": round(float(r.Open), 2), "h": round(float(r.High), 2),
                           "l": round(float(r.Low), 2),  "c": round(float(r.Close), 2),
                           "v": int(r.Volume)}

keys = sorted(rows)
meta = {"symbol": SYMBOL, "source": "TradeStation", "unit": "Daily",
        "generated_at": now_et.strftime("%Y-%m-%d %H:%M %Z"),
        "first": keys[0], "last": keys[-1], "sessions": len(keys)}

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* SPX daily OHLC -- GENERATED by build_prices.py. Do not hand-edit.\n"
            "   Re-run the script to refresh. Source: TradeStation $SPX.X daily bars. */\n")
    f.write("window.SPX_META = " + json.dumps(meta) + ";\n")
    f.write("window.SPX_DAILY = " + json.dumps(rows, sort_keys=True, separators=(",", ":")) + ";\n")

print("sessions written:", len(keys))
print("range:", keys[0], "->", keys[-1])
if skipped: print("skipped in-progress session:", skipped)
print("bytes:", os.path.getsize(OUT))
